/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ApplicationRequirementsRouteImport } from './routes/application-requirements'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRequirementsRoute = ApplicationRequirementsRouteImport.update({
  id: '/application-requirements',
  path: '/application-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/application-requirements': typeof ApplicationRequirementsRoute
  '/info': typeof InfoRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-requirements': typeof ApplicationRequirementsRoute
  '/info': typeof InfoRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/application-requirements': typeof ApplicationRequirementsRoute
  '/info': typeof InfoRoute
  '/newsletter': typeof NewsletterRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-requirements'
    | '/info'
    | '/newsletter'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/application-requirements' | '/info' | '/newsletter' | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/application-requirements'
    | '/info'
    | '/newsletter'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationRequirementsRoute: typeof ApplicationRequirementsRoute
  InfoRoute: typeof InfoRoute
  NewsletterRoute: typeof NewsletterRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-requirements': {
      id: '/application-requirements'
      path: '/application-requirements'
      fullPath: '/application-requirements'
      preLoaderRoute: typeof ApplicationRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationRequirementsRoute: ApplicationRequirementsRoute,
  InfoRoute: InfoRoute,
  NewsletterRoute: NewsletterRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
